// <auto-generated />
namespace Express_Report_Folders.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v001003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v001003));
        
        string IMigrationMetadata.Id
        {
            get { return "201703071234564_v001.003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
